# baseURL = 'http://124.22.1.106.196:8081/'
baseURL = "https://bairdl.github.io/xhao-blog/"
languageCode = 'zh-CN'
title = "XHao's blog"
theme = "simple-paper"
ignoreFiles = [
    "themes/.*/content/.*",
    "content/todo.md",
]
enableGitInfo = true

[outputs]
home = ["HTML", "SearchIndex"]

[frontmatter]
# lastmod = ["lastmod", ":fileModTime", ":default"]
lastmod = ["lastmod", ":git", ":fileModTime", ":default"]
