[[main]]
name = '主页'
pageRef = '/'
weight = 10

[[main]]
name = '文章'
pageRef = '/posts'
weight = 20

[[main]]
name = '标签'
pageRef = '/tags'
weight = 30

[[main]]
name = '分类'
pageRef = '/categories'
weight = 40

[[main]]
name = "统计"
pageRef = "/stats/"
weight = 50